# Docker Compose 文件的版本
version: "3.8"

# 定义我们要运行的服务
services:
  # 服务的名字，我们叫它 db
  db:
    # 指定使用哪个官方镜像，这里是最新版的 postgres
    image: postgres:latest
    # 如果服务意外停止，总是尝试重启
    restart: always
    # 设置容器的环境变量，用于初始化数据库
    environment:
      POSTGRES_USER: your_db_user # 设置数据库用户名
      POSTGRES_PASSWORD: your_db_password # 设置数据库密码
      POSTGRES_DB: your_db_name # 设置数据库名称
    # 将容器的 5432 端口映射到我们电脑的 5432 端口
    # 这样我们的 Node.js 应用就能通过 localhost:5432 连接到它
    ports:
      - "5432:5432"
    # 数据持久化设置，确保即使容器被删除，我们的数据也不会丢失
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

# 定义数据卷
volumes:
  postgres-data:
